# -*- coding: utf-8 -*-
"""
Created on 2016/10/11 11:27

@author: qiding
"""


stk_func_dict = {
    'date': 'last',
    'coid': 'last',
    'newprice': 'last',
    'totalvolume': 'sum',
    'totalamount': 'sum',
    'totaltransaction': 'sum',
    'buytrans': 'sum',
    'buyvolume': 'sum',
    'buyamount': 'sum',
    'selltrans': 'sum',
    'sellvolume': 'sum',
    'sellamount': 'sum',
    'ask10': 'last',
    'ask9': 'last',
    'ask8': 'last',
    'ask7': 'last',
    'ask6': 'last',
    'ask5': 'last',
    'ask4': 'last',
    'ask3': 'last',
    'ask2': 'last',
    'ask1': 'last',
    'bid1': 'last',
    'bid2': 'last',
    'bid3': 'last',
    'bid4': 'last',
    'bid5': 'last',
    'bid6': 'last',
    'bid7': 'last',
    'bid8': 'last',
    'bid9': 'last',
    'bid10': 'last',
    'asize10': 'last',
    'asize9': 'last',
    'asize8': 'last',
    'asize7': 'last',
    'asize6': 'last',
    'asize5': 'last',
    'asize4': 'last',
    'asize3': 'last',
    'asize2': 'last',
    'asize1': 'last',
    'bsize1': 'last',
    'bsize2': 'last',
    'bsize3': 'last',
    'bsize4': 'last',
    'bsize5': 'last',
    'bsize6': 'last',
    'bsize7': 'last',
    'bsize8': 'last',
    'bsize9': 'last',
    'bsize10': 'last',
}
